// Code generated by "stringer --type Role"; DO NOT EDIT.

package rbac

import "strconv"

const _Role_name = "ReaderWriterAdmin"

var _Role_index = [...]uint8{0, 6, 12, 17}

func (i Role) String() string {
	if i < 0 || i >= Role(len(_Role_index)-1) {
		return "Role(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}
